[pytest]
addopts = 
    --alluredir=output/allure-results
    --clean-alluredir
    --video=retain-on-failure
    --screenshot=only-on-failure
    -v
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    mobile: мобильные тесты
    e2e: сквозные сценарии
    responsive: проверка адаптивности
    touch: тач-события
    performance: замеры производительности
    slow: медленные тесты

# Фильтрация предупреждений
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning